name: Sphinx
env:
  POETRY_VERSION: 1.3.1
  POETRY_URL: https://install.python-poetry.org
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | \
            python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sphinx build
        run: poetry run sphinx-apidoc -f -o docs/source/ src/
      - name: Make HTML
        run: sphinx-build docs/source/ docs/build/ -a
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
